/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyLopDemo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BaoThiForm extends javax.swing.JFrame {
    private ArrayList<BaoThi> list = new ArrayList<>();
    private ArrayList<Lop> listLop = new ArrayList<>();
    private ArrayList<SinhVien> listSv = new ArrayList<>();
    private String maGv;
    private IOFile file;
    private DefaultTableModel tblModel = new DefaultTableModel();
    /**
     * Creates new form BaoThiForm
     */
    public BaoThiForm(String maGv) {
        initComponents();
        this.maGv = maGv;
        file = new IOFile();
        listLop = file.doc("dbLop.txt");
        listSv = file.doc("dbSinhVien.txt");
        initTable();
        fillTable();
    }

    private BaoThiForm() {
        
    }
    private void fillTable(){
        tblModel.setRowCount(0);
        
        list = file.doc("dbBaoThi.txt");
        
        for(BaoThi tb : list){
            if(tb.getMaGv().equals(maGv)){
                tblModel.addRow(new Object[]{tb.getMaBt(),tb.getMaSv(),tb.getNoiDung(),});
            }
        }
        
        
        tblModel.fireTableDataChanged();
    }
    
    private void initTable(){
        String[] cot = new String[]{"Mã Thông báo","Mã Sinh Viên","Nội dung"};
        
        tblModel.setColumnIdentifiers(cot);
        
        tblBt.setModel(tblModel);
    }
    private int check(String maSv){
        int dem = 0;
        ArrayList<Lop> listDemo = new ArrayList<>();
        for(Lop lop : listLop){
            if(lop.getMaGiaoVien().equals(maGv)){
                listDemo.add(lop);
            }
        }
        for(SinhVien sv : listSv){
            for(Lop lop : listDemo){
                if(sv.getMaSv().equals(txtMaSinhVien.getText())&&sv.getMaLop().equals(lop.getMaLop())){
                   dem++; 
                }
            }
        }
        if(dem==0){
            return 0;
        }else return 1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBt = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Báo Thi");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã báo thi: ");

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nội Dung");

        txtNoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Câp Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        tblBt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBt);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã Sinh Viên: ");

        txtMaSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMaSinhVien, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addGap(42, 42, 42)
                .addComponent(btnCapNhat)
                .addGap(50, 50, 50)
                .addComponent(btnNhapMoi)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnNhapMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
            // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtMa.getText().equals("")){
            sb.append("Mã thông báo không được để trống \n");
            txtMa.setBackground(Color.red);
        }else{
            txtMa.setBackground(Color.white);
        }
        if(txtMaSinhVien.getText().equals("")){
            sb.append("Mã sinh viên không được để trống \n");
            txtMaSinhVien.setBackground(Color.red);
        }else{
            txtMaSinhVien.setBackground(Color.white);
        }
        if(txtNoiDung.getText().equals("")){
            sb.append("Nội dung thông báo không được để trống \n");
            txtNoiDung.setBackground(Color.red);
        }else{
            txtNoiDung.setBackground(Color.white);
        }
        for(BaoThi tb : list){
            if(txtMa.getText().equals(tb.getMaBt())){
                sb.append("Mã thông báo đã tồn tại \n");
                txtMa.setBackground(Color.red);
            }
        }
        if(check(txtMaSinhVien.getText())==0){
            sb.append("Sinh viên không thuộc quản lý của bạn \n");
            txtMa.setBackground(Color.red);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        BaoThi tb = new BaoThi();
        try {
            tb.setMaBt(txtMa.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        tb.setNoiDung(txtNoiDung.getText());
        tb.setMaSv(txtMaSinhVien.getText());
        tb.setMaGv(maGv);
        
        list.add(tb);
        
        file.ghi(list, "dbBaoThi.txt");
        
        fillTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        txtMa.setText("");
        txtNoiDung.setText("");
        txtMaSinhVien.setText("");
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtMa.getText().equals("")){
            sb.append("Mã thông báo không được để trống \n");
            txtMa.setBackground(Color.red);
        }else{
            txtMa.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if(luaChon == JOptionPane.NO_OPTION){
            return;
        }
        for(BaoThi tb : list){
            if(tb.getMaBt().equals(txtMa.getText())){
                list.remove(tb);
                break;
            }
        }
        file.ghi(list, "dbBaoThi.txt");
        
        fillTable();
        
        btnNhapMoiActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtMa.getText().equals("")){
            sb.append("Mã thông báo không được để trống \n");
            txtMa.setBackground(Color.red);
        }else{
            txtMa.setBackground(Color.white);
        }
        if(txtMaSinhVien.getText().equals("")){
            sb.append("Mã sinh viên không được để trống \n");
            txtMaSinhVien.setBackground(Color.red);
        }else{
            txtMaSinhVien.setBackground(Color.white);
        }
        if(txtNoiDung.getText().equals("")){
            sb.append("Nội dung thông báo không được để trống \n");
            txtNoiDung.setBackground(Color.red);
        }else{
            txtNoiDung.setBackground(Color.white);
        }
        if(check(txtMaSinhVien.getText())==0){
            sb.append("Sinh viên không thuộc quản lý của bạn \n");
            txtMa.setBackground(Color.red);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật thông tin không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if(luaChon == JOptionPane.NO_OPTION){
            return;
        }
        for(BaoThi tb : list){
            if(tb.getMaBt().equals(txtMa.getText())){
                tb.setNoiDung(txtNoiDung.getText());
                tb.setMaSv(txtMaSinhVien.getText());
                break;
            }
        }
        file.ghi(list, "dbBaoThi.txt");
        
        fillTable();
        
        btnNhapMoiActionPerformed(evt);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBtMouseClicked
        // TODO add your handling code here:
        int chonDong = tblBt.getSelectedRow();
        
        if(chonDong>=0){
            String maTb = (String) tblBt.getValueAt(chonDong, 0);
            
            for(BaoThi tb : list){
                if(maTb.equals(tb.getMaBt())){
                    txtMa.setText(tb.getMaBt());
                    txtNoiDung.setText(tb.getNoiDung());
                    txtMaSinhVien.setText(tb.getMaSv());
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblBtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoThiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoThiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoThiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoThiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoThiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblBt;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
