/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyLopDemo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TBRutHocPhanForm extends javax.swing.JFrame {
    private ArrayList<TBRutHocPhan> list = new ArrayList<>();
    private ArrayList<Lop> listLop = new ArrayList<>();
    private ArrayList<SinhVien> listSv = new ArrayList<>();
    private String maGv;
    private IOFile file;
    private DefaultTableModel tblModel = new DefaultTableModel();
    /**
     * Creates new form TBRutHocPhanForm
     */
    public TBRutHocPhanForm(String maGv) {
        initComponents();
        
        this.maGv = maGv;
        file = new IOFile();
        listLop = file.doc("dbLop.txt");
        listSv = file.doc("dbSinhVien.txt");
        initTable();
        fillTable();
        
        
    }

    private TBRutHocPhanForm() {
        
    }
    
    private void fillTable(){
        tblModel.setRowCount(0);
        
        list = file.doc("dbTbr.txt");
        
        for(TBRutHocPhan tb : list){
            if(tb.getMaGv().equals(maGv)){
                tblModel.addRow(new Object[]{tb.getMaTb(),tb.getMaSv(),tb.getNoiDung(),});
            }
        }
        
        
        tblModel.fireTableDataChanged();
    }
    
    private void initTable(){
        String[] cot = new String[]{"Mã Thông báo","Mã Sinh Viên","Nội dung"};
        
        tblModel.setColumnIdentifiers(cot);
        
        tblTb.setModel(tblModel);
    }
    private int check(String maSv){
        int dem = 0;
        ArrayList<Lop> listDemo = new ArrayList<>();
        for(Lop lop : listLop){
            if(lop.getMaGiaoVien().equals(maGv)){
                listDemo.add(lop);
            }
        }
        for(SinhVien sv : listSv){
            for(Lop lop : listDemo){
                if(sv.getMaSv().equals(txtMaSinhVien.getText())&&sv.getMaLop().equals(lop.getMaLop())){
                    dem++;
                }
            }
        }
        if(dem==0){
            return 0;
        }else return 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTb = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtThem = new javax.swing.JButton();
        txtXoa = new javax.swing.JButton();
        txtCapNhat = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông Báo Rút Học Phần");

        tblTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTb);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã Thông báo: ");

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nội dung: ");

        txtNoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtThem.setText("Thêm");
        txtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemActionPerformed(evt);
            }
        });

        txtXoa.setText("Xóa");
        txtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXoaActionPerformed(evt);
            }
        });

        txtCapNhat.setText("Cập Nhật");
        txtCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapNhatActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã Sinh Viên: ");

        txtMaSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtThem)
                .addGap(41, 41, 41)
                .addComponent(txtXoa)
                .addGap(44, 44, 44)
                .addComponent(txtCapNhat)
                .addGap(67, 67, 67)
                .addComponent(btnNhapMoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThem)
                    .addComponent(txtXoa)
                    .addComponent(txtCapNhat)
                    .addComponent(btnNhapMoi))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnBack)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTbMouseClicked
        // TODO add your handling code here:
        int chonDong = tblTb.getSelectedRow();
        
        if(chonDong>=0){
            String maTb = (String) tblTb.getValueAt(chonDong, 0);
            
            for(TBRutHocPhan tb : list){
                if(maTb.equals(tb.getMaTb())){
                    txtMa.setText(tb.getMaTb());
                    txtNoiDung.setText(tb.getNoiDung());
                    txtMaSinhVien.setText(tb.getMaSv());
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblTbMouseClicked

    private void txtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtMa.getText().equals("")){
            sb.append("Mã thông báo không được để trống \n");
            txtMa.setBackground(Color.red);
        }else{
            txtMa.setBackground(Color.white);
        }
        if(txtMaSinhVien.getText().equals("")){
            sb.append("Mã sinh viên không được để trống \n");
            txtMaSinhVien.setBackground(Color.red);
        }else{
            txtMaSinhVien.setBackground(Color.white);
        }
        if(txtNoiDung.getText().equals("")){
            sb.append("Nội dung thông không được để trống \n");
            txtNoiDung.setBackground(Color.red);
        }else{
            txtNoiDung.setBackground(Color.white);
        }
        for(TBRutHocPhan tb : list){
            if(txtMa.getText().equals(tb.getMaTb())){
                sb.append("Mã thông báo đã tồn tại \n");
                txtMa.setBackground(Color.red);
            }
        }
        if(check(txtMaSinhVien.getText())==0){
            sb.append("Sinh viên không thuộc quản lý của bạn \n");
            txtMa.setBackground(Color.red);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        TBRutHocPhan tb = new TBRutHocPhan();
        try {
            tb.setMaTb(txtMa.getText());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        tb.setNoiDung(txtNoiDung.getText());
        tb.setMaSv(txtMaSinhVien.getText());
        tb.setMaGv(maGv);
        
        list.add(tb);
        
        file.ghi(list, "dbTbr.txt");
        
        fillTable();
    }//GEN-LAST:event_txtThemActionPerformed

    private void txtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtMa.getText().equals("")){
            sb.append("Mã thông báo không được để trống \n");
            txtMa.setBackground(Color.red);
        }else{
            txtMa.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if(luaChon == JOptionPane.NO_OPTION){
            return;
        }
        for(TBRutHocPhan tb : list){
            if(tb.getMaTb().equals(txtMa.getText())){
                list.remove(tb);
                break;
            }
        }
        file.ghi(list, "dbTbr.txt");
        
        fillTable();
        
        btnNhapMoiActionPerformed(evt);
    }//GEN-LAST:event_txtXoaActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        txtMa.setText("");
        txtNoiDung.setText("");
        txtMaSinhVien.setText("");
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void txtCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapNhatActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtMa.getText().equals("")){
            sb.append("Mã thông báo không được để trống \n");
            txtMa.setBackground(Color.red);
        }else{
            txtMa.setBackground(Color.white);
        }
        if(txtMaSinhVien.getText().equals("")){
            sb.append("Mã sinh viên không được để trống \n");
            txtMaSinhVien.setBackground(Color.red);
        }else{
            txtMaSinhVien.setBackground(Color.white);
        }
        if(txtNoiDung.getText().equals("")){
            sb.append("Nội dung thông không được để trống \n");
            txtNoiDung.setBackground(Color.red);
        }else{
            txtNoiDung.setBackground(Color.white);
        }
        if(check(txtMaSinhVien.getText())==0){
            sb.append("Sinh viên không thuộc quản lý của bạn \n");
            txtMa.setBackground(Color.red);
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString(),"Error",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật thông tin không?","Hỏi",JOptionPane.YES_NO_OPTION);
        if(luaChon == JOptionPane.NO_OPTION){
            return;
        }
        for(TBRutHocPhan tb : list){
            if(tb.getMaTb().equals(txtMa.getText())){
                tb.setNoiDung(txtNoiDung.getText());
                tb.setMaSv(txtMaSinhVien.getText());
                break;
            }
        }
        file.ghi(list, "dbTbr.txt");
        
        fillTable();
        
        btnNhapMoiActionPerformed(evt);
    }//GEN-LAST:event_txtCapNhatActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TBRutHocPhanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TBRutHocPhanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TBRutHocPhanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TBRutHocPhanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TBRutHocPhanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblTb;
    private javax.swing.JButton txtCapNhat;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JButton txtThem;
    private javax.swing.JButton txtXoa;
    // End of variables declaration//GEN-END:variables
}
